import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-slate-600 text-white flex items-center h-16 px-2 sticky top-0">
          <Link href="/">Just About: User Management</Link>
        </nav>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
